# Generated by Django 4.2.4 on 2023-08-18 12:00

from django.db import migrations, models
import users.services.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="auth_code",
            new_name="otp",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=15, unique=True, validators=[users.services.validators.validate_phone]),
        ),
    ]
