# Generated by Django 4.2.4 on 2023-08-21 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_created_at_pendinguser_otp_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PendingUser",
        ),
    ]
